### ISSUE TITLE
Dataset for help?

### ISSUE THREAD

**Issue by trueWangSyutung** [Jinfeng-Xu/FKAN-GCF#2]
Hello, I'm a graduate student from Chinese mainland Tianjin University of Technology.

I saw your published paper "FourierKAN-GCF: Fourier Kolmogorov-Arnold Network - An
Effective and Efficient Feature Transformation for Graph
Collaborative Filtering"

I want to study your code, but the data set can't find the format consistent with the requirements in your code.

So I want to ask, what should I do with the data set downloaded from the data set web page provided in the paper?

If so, can you send me a copy of what you use?

ValueError: File /home/wxd2zrx/document/FKAN-GCF-main/data/mooc.inter not exist

**Comment by Jinfeng-Xu** [comment]
> Hello, I'm a graduate student from Chinese mainland Tianjin University of Technology.
> 
> I saw your published paper "FourierKAN-GCF: Fourier Kolmogorov-Arnold Network - An Effective and Efficient Feature Transformation for Graph Collaborative Filtering"
> 
> I want to study your code, but the data set can't find the format consistent with the requirements in your code.
> 
> So I want to ask, what should I do with the data set downloaded from the data set web page provided in the paper?
> 
> If so, can you send me a copy of what you use?
> 
> ValueError: File /home/wxd2zrx/document/FKAN-GCF-main/data/mooc.inter not exist

Dear Wang,

Many thanks for your interests,
You are getting your hands dirty on the code and datasets. 
The original MOOC datasets we used for recommendation are as follows : [HRL](https://github.com/jerryhao66/HRL) 
moocdata.cn holds the detailed logs of MOOC dataset.

For Amazon datasets, please handle it by [RecBole](https://github.com/RUCAIBox/RecBole).

Best,

**Comment by trueWangSyutung** [comment]
I would like to ask, what pyhton libraries have you used?
